apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-with-helm-deployment
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: ComponentVersion
    name: ocm-with-helm
    resourceRef:
      name: backend-app-chart
      version: latest
  snapshotTemplate:
    name: ocm-with-helm-snapshot-deployment      


# apiVersion: delivery.ocm.software/v1alpha1
# kind: Resource
# metadata:
#   name: ocm-with-helm-deployment
#   namespace: ocm-system
# spec:
#   interval: 10m0s
#   componentVersionRef:
#     name: ocm-with-helm
#     namespace: ocm-system
#   resource:
#     name: backend-app-chart
#   snapshotTemplate:
#     name: ocm-with-helm-snapshot-deployment
